/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sistema.manha;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;


public class Autenticacao extends javax.swing.JInternalFrame {

    /**
     * Creates new form Autenticacao
     */
    public Autenticacao() {
        super("Tela de Autenticação de Usuário",
        false,true,false,false);
        initComponents();
        Toolkit monitor=Toolkit.getDefaultToolkit();
        final Dimension tamanho=
                monitor.getScreenSize();
        int largura=(int)tamanho.getWidth();
        int altura=(int)tamanho.getHeight();
        this.setLocation((largura-550)/2,(altura-300)/2);
        getRootPane().setDefaultButton(btnAutenticar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsuario = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        btnFechar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnAutenticar = new javax.swing.JButton();
        txtSenha = new javax.swing.JPasswordField();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        itemAutenticar = new javax.swing.JMenuItem();
        itemLimpar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itemFechar = new javax.swing.JMenuItem();

        lblUsuario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblUsuario.setText("Usuário");

        lblSenha.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblSenha.setText("Senha");

        txtUsuario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        btnFechar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnLimpar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnAutenticar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnAutenticar.setText("Autenticar");
        btnAutenticar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutenticarActionPerformed(evt);
            }
        });

        txtSenha.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        menuArquivo.setText("Arquivo");

        itemAutenticar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.CTRL_MASK));
        itemAutenticar.setText("Autenticar");
        itemAutenticar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAutenticarActionPerformed(evt);
            }
        });
        menuArquivo.add(itemAutenticar);

        itemLimpar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        itemLimpar.setText("Limpar");
        itemLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLimparActionPerformed(evt);
            }
        });
        menuArquivo.add(itemLimpar);
        menuArquivo.add(jSeparator1);

        itemFechar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        itemFechar.setText("Fechar");
        itemFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemFecharActionPerformed(evt);
            }
        });
        menuArquivo.add(itemFechar);

        jMenuBar1.add(menuArquivo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSenha)
                            .addComponent(lblUsuario))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsuario)
                            .addComponent(txtSenha))
                        .addGap(45, 45, 45))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnFechar)
                        .addGap(66, 66, 66)
                        .addComponent(btnLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(btnAutenticar)
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSenha)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar)
                    .addComponent(btnLimpar)
                    .addComponent(btnAutenticar))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtUsuario.setText("");
        txtSenha.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnAutenticarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutenticarActionPerformed
        String usuario=txtUsuario.getText().toString();
        String senha=txtSenha.getText().toString();
        //aqui neste local precisa conectar o banco
        try
        {
            ResultSet registros=null;
            PreparedStatement consultar=
            Principal.conexao.prepareStatement
            ("SELECT COUNT(*) as numero FROM autenticar WHERE usuario='"
            + usuario + "' AND senha='" + senha + "'");
            registros=consultar.executeQuery();
            registros.next();
            int quantidade=Integer.parseInt
            (registros.getString("numero"));
            if (quantidade!=0)
            {
                Principal.itemLogoff.setVisible(true);
                Principal.menuEnderecos.setVisible(true);
                Principal.menuAparencia.setVisible(true);
                Principal.itemAutenticar.setVisible(false);
                Principal.menuRelogio.setVisible(true);
                Principal.menuAgenda.setVisible(true);
                dispose();
            }else
            {
                JOptionPane.showMessageDialog(null,
                "Usuário ou senha incorretos!!!",
                "Acesso Negado",
                JOptionPane.ERROR_MESSAGE);
                txtUsuario.requestFocus();
            }
        }catch (SQLException e)
        {
            JOptionPane.showMessageDialog(null,
            "Erro de SQL: " + e.getMessage(),
            "Erro",JOptionPane.ERROR_MESSAGE);
        }catch (Exception e )
        {
            JOptionPane.showMessageDialog(null,
            "Erro: " + e.getMessage(),
            "Erro",JOptionPane.ERROR_MESSAGE);
        }        
    }//GEN-LAST:event_btnAutenticarActionPerformed

    private void itemFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemFecharActionPerformed
        this.btnFecharActionPerformed(evt);
    }//GEN-LAST:event_itemFecharActionPerformed

    private void itemLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLimparActionPerformed
        this.btnLimparActionPerformed(evt);
    }//GEN-LAST:event_itemLimparActionPerformed

    private void itemAutenticarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAutenticarActionPerformed
        this.btnAutenticarActionPerformed(evt);
    }//GEN-LAST:event_itemAutenticarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutenticar;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JMenuItem itemAutenticar;
    private javax.swing.JMenuItem itemFechar;
    private javax.swing.JMenuItem itemLimpar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
