/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sistema.manha;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Jason Santos
 */
public class CadastrarAlterarContatos extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastrarAlterarContato
     */
    public CadastrarAlterarContatos() {
        super("Cadastrar Contatos",
        false,true,false,false);
        //titulo,redimensionar,fechar,
        //maximizar,minimizar
        this.setLocation(80,80);
        initComponents();
        btnCadastrarAlterar.setText("Cadastrar");
        itemCadastrarAlterar.setText("Cadastrar");
        getRootPane().setDefaultButton
        (btnCadastrarAlterar);
    }
    
    public CadastrarAlterarContatos
        (String nome,String telefone)
    {
        super("Alterar Contatos",false,true,
                false,false);
        this.setLocation(80,80);
        initComponents();
        nomeAtual=nome;
        telefoneAtual=telefone;        
        txtNome.setText(nome);
        txtTelefone.setText(telefone);        
        btnCadastrarAlterar.setText("Alterar");
        itemCadastrarAlterar.setText("Alterar");
        getRootPane().setDefaultButton
        (btnCadastrarAlterar);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JFormattedTextField();
        btnCadastrarAlterar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemCadastrarAlterar = new javax.swing.JMenuItem();
        itemLimpar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itemFechar = new javax.swing.JMenuItem();

        lblNome.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblNome.setText("Nome");

        lblTelefone.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTelefone.setText("Telefone");

        txtNome.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        btnCadastrarAlterar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnCadastrarAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarAlterarActionPerformed(evt);
            }
        });

        btnLimpar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnFechar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        jMenu1.setText("Arquivo");

        itemCadastrarAlterar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.CTRL_MASK));
        itemCadastrarAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCadastrarAlterarActionPerformed(evt);
            }
        });
        jMenu1.add(itemCadastrarAlterar);

        itemLimpar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        itemLimpar.setText("Limpar");
        itemLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLimparActionPerformed(evt);
            }
        });
        jMenu1.add(itemLimpar);
        jMenu1.add(jSeparator1);

        itemFechar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        itemFechar.setText("Fechar");
        itemFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemFecharActionPerformed(evt);
            }
        });
        jMenu1.add(itemFechar);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnCadastrarAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnLimpar)
                        .addGap(37, 37, 37)
                        .addComponent(btnFechar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNome)
                            .addComponent(lblTelefone))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTelefone)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTelefone)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCadastrarAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtNome.setText("");
        txtTelefone.setText("");
        txtNome.requestFocus();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnCadastrarAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarAlterarActionPerformed
        if (txtNome.getText().equals(""))
        {
            JOptionPane.showMessageDialog
            (null,"Digite o nome!!!",
             "Nome",JOptionPane.ERROR_MESSAGE);
            txtNome.requestFocus();
        }else if (txtTelefone.getText().equals("(  )    -    "))
        {
            JOptionPane.showMessageDialog
            (null,"Digite o telefone!!!",
             "Telefone",JOptionPane.ERROR_MESSAGE);
            txtTelefone.requestFocus();
        }else if (btnCadastrarAlterar.getText().
                equals("Cadastrar"))
        {
            try
            {
                PreparedStatement cadastrar=
                Principal.conexao.prepareStatement
                ("INSERT INTO contatos(nome,telefone) VALUES(?,?)");
                cadastrar.setString(1,txtNome.getText().toUpperCase());
                cadastrar.setString(2,txtTelefone.getText());                    
                cadastrar.executeUpdate();
                JOptionPane.showMessageDialog(null,
                "Contato cadastrado com sucesso!!!",
                "Cadastrado",JOptionPane.INFORMATION_MESSAGE);
                dispose();
            }catch(SQLException e)
            {
                JOptionPane.showMessageDialog(null,
                "Erro de SQL: " + e.getMessage(),"Erro",
                JOptionPane.ERROR_MESSAGE);
            }catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,
                "Erro: " + e.getMessage(),"Erro",
                JOptionPane.ERROR_MESSAGE);
            }
        }else if (btnCadastrarAlterar.getText().
                equals("Alterar"))
        {
            Object[] opcoes={"Sim","Não"};
            int retorno=JOptionPane.showOptionDialog
            (null,"Tem certeza que deseja alterar?",
            "Alterar",JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE,null,
            opcoes,opcoes[0]);
            if (retorno==0)
            {
                try
                {
                    PreparedStatement alterar=
                    Principal.conexao.prepareStatement
                    ("UPDATE contatos SET nome=?,telefone=? WHERE nome=? AND telefone=?");
                    alterar.setString(1,txtNome.getText().toUpperCase());
                    if (txtTelefone.getText().equals("(  )    -    "))
                        alterar.setString(2,"");
                    else
                        alterar.setString(2,txtTelefone.getText());                    
                    alterar.setString(3,nomeAtual);
                    alterar.setString(4,telefoneAtual);                    
                    alterar.executeUpdate();
                    JOptionPane.showMessageDialog(null,
                    "Contato alterado com sucesso!!!",
                    "Contato Alterado",
                    JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                }catch(SQLException e)
                {
                    JOptionPane.showMessageDialog(null,
                    "Erro de SQL: " + e.getMessage(),
                    "Erro",JOptionPane.ERROR_MESSAGE);
                }catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,
                    "Erro: " + e.getMessage(),
                    "Erro",JOptionPane.ERROR_MESSAGE);
                }
            }
        }        
    }//GEN-LAST:event_btnCadastrarAlterarActionPerformed

    private void itemCadastrarAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadastrarAlterarActionPerformed
        this.btnCadastrarAlterarActionPerformed(evt);
    }//GEN-LAST:event_itemCadastrarAlterarActionPerformed

    private void itemLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLimparActionPerformed
        this.btnLimparActionPerformed(evt);
    }//GEN-LAST:event_itemLimparActionPerformed

    private void itemFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemFecharActionPerformed
        this.btnFecharActionPerformed(evt);
    }//GEN-LAST:event_itemFecharActionPerformed

    private String nomeAtual,telefoneAtual;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarAlterar;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JMenuItem itemCadastrarAlterar;
    private javax.swing.JMenuItem itemFechar;
    private javax.swing.JMenuItem itemLimpar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
