/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sistema.manha;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Jason Santos
 */
public class CadastrarAlterarEnderecos extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastrarAlterarEnderecos
     */
    public CadastrarAlterarEnderecos() {
        super("Cadastrar Endereços",
        false,true,false,false);
        //titulo,redimensionar,fechar,
        //maximizar,minimizar
        this.setLocation(80,80);
        initComponents();
        btnCadastrarAlterar.setText("Cadastrar");
        itemCadastrarAlterar.setText("Cadastrar");
        txtCidade.setText("Caxias do Sul");
        cboEstado.setSelectedItem("RS");
        getRootPane().setDefaultButton
        (btnCadastrarAlterar);
    }
    
    public CadastrarAlterarEnderecos
        (String rua,String cep,String bairro,
                String cidade,String estado)
    {
        super("Alterar Endereço",false,true,
                false,false);
        this.setLocation(80,80);
        initComponents();
        ruaAtual=rua;
        cepAtual=cep;
        bairroAtual=bairro;
        cidadeAtual=cidade;
        estadoAtual=estado;
        txtRua.setText(rua);
        txtCep.setText(cep);
        txtBairro.setText(bairro);
        txtCidade.setText(cidade);
        cboEstado.setSelectedItem(estado);
        btnCadastrarAlterar.setText("Alterar");
        itemCadastrarAlterar.setText("Alterar");
        getRootPane().setDefaultButton
        (btnCadastrarAlterar);
    }            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRua = new javax.swing.JLabel();
        lblBairro = new javax.swing.JLabel();
        lblCidade = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        txtRua = new javax.swing.JTextField();
        lblCep = new javax.swing.JLabel();
        txtCep = new javax.swing.JFormattedTextField();
        txtBairro = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        cboEstado = new javax.swing.JComboBox();
        btnCadastrarAlterar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        itemCadastrarAlterar = new javax.swing.JMenuItem();
        itemLimpar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itemFechar = new javax.swing.JMenuItem();

        lblRua.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblRua.setText("Rua");

        lblBairro.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblBairro.setText("Bairro");

        lblCidade.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCidade.setText("Cidade");

        lblEstado.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblEstado.setText("Estado");

        txtRua.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        lblCep.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCep.setText("CEP");

        try {
            txtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCep.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        txtBairro.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        txtCidade.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        cboEstado.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cboEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "RS", "SC", "PR" }));

        btnCadastrarAlterar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnCadastrarAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarAlterarActionPerformed(evt);
            }
        });

        btnLimpar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnFechar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        menuArquivo.setText("Arquivo");

        itemCadastrarAlterar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.CTRL_MASK));
        itemCadastrarAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCadastrarAlterarActionPerformed(evt);
            }
        });
        menuArquivo.add(itemCadastrarAlterar);

        itemLimpar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        itemLimpar.setText("Limpar");
        itemLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLimparActionPerformed(evt);
            }
        });
        menuArquivo.add(itemLimpar);
        menuArquivo.add(jSeparator1);

        itemFechar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        itemFechar.setText("Fechar");
        itemFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemFecharActionPerformed(evt);
            }
        });
        menuArquivo.add(itemFechar);

        jMenuBar1.add(menuArquivo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCidade)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCidade))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblBairro)
                                                .addGap(18, 18, 18))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(lblRua)
                                                .addGap(40, 40, 40)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addComponent(lblCep)
                                .addGap(18, 18, 18)
                                .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEstado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCadastrarAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(btnLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFechar)
                        .addGap(62, 62, 62))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRua)
                    .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCep)
                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBairro)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCidade)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstado)
                    .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpar)
                    .addComponent(btnFechar)
                    .addComponent(btnCadastrarAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtRua.setText("");
        txtCep.setText("");
        txtBairro.setText("");
        txtCidade.setText("Caxias do Sul");
        cboEstado.setSelectedItem("RS");
        txtRua.requestFocus();
        //cursor piscando no campo rua
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnCadastrarAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarAlterarActionPerformed
        if (txtRua.getText().equals(""))
        {
            JOptionPane.showMessageDialog
            (null,"Digite o nome da rua!!!",
             "Rua",JOptionPane.ERROR_MESSAGE);
            txtRua.requestFocus();
        }else if (txtBairro.getText().equals(""))
        {
            JOptionPane.showMessageDialog
            (null,"Digite o nome do bairro!!!",
             "Bairro",JOptionPane.ERROR_MESSAGE);
            txtBairro.requestFocus();
        }else if (txtCidade.getText().equals(""))
        {
            JOptionPane.showMessageDialog
            (null,"Digite o nome da cidade!!!",
             "Cidade",JOptionPane.ERROR_MESSAGE);
            txtCidade.requestFocus();
        }else if (btnCadastrarAlterar.getText()
                .equals("Cadastrar"))
        {
            try
            {
                PreparedStatement cadastrar=
                Principal.conexao.prepareStatement
                ("INSERT INTO enderecos(rua,cep,bairro,cidade,estado) VALUES(?,?,?,?,?)");
                cadastrar.setString(1,txtRua.getText().toUpperCase());
                if (txtCep.getText().equals("     -   "))
                    cadastrar.setString(2,"");
                else
                    cadastrar.setString(2,txtCep.getText());
                cadastrar.setString(3,txtBairro.getText().toUpperCase());
                cadastrar.setString(4,txtCidade.getText().toUpperCase());
                cadastrar.setString(5,
                cboEstado.getSelectedItem().toString());
                cadastrar.executeUpdate();
                JOptionPane.showMessageDialog(null,
                "Endereço cadastrado com sucesso!!!",
                "Cadastrado",JOptionPane.INFORMATION_MESSAGE);
                dispose();
            }catch(SQLException e)
            {
                JOptionPane.showMessageDialog(null,
                "Erro de SQL: " + e.getMessage(),"Erro",
                JOptionPane.ERROR_MESSAGE);
            }catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,
                "Erro: " + e.getMessage(),"Erro",
                JOptionPane.ERROR_MESSAGE);
            }
        }else if (btnCadastrarAlterar.getText()
                .equals("Alterar"))
        {
            Object[] opcoes={"Sim","Não"};
            int retorno=JOptionPane.showOptionDialog
            (null,"Tem certeza que deseja alterar?",
            "Alterar",JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE,null,
            opcoes,opcoes[0]);
            if (retorno==0)
            {
                try
                {
                    PreparedStatement alterar=
                    Principal.conexao.prepareStatement
                    ("UPDATE enderecos SET rua=?,cep=?,bairro=?,cidade=?,estado=? WHERE rua=? AND cep=? AND bairro=? AND cidade=? AND estado=?");
                    alterar.setString(1,txtRua.getText().toUpperCase());
                    if (txtCep.getText().equals("     -   "))
                        alterar.setString(2,"");
                    else
                        alterar.setString(2,txtCep.getText());
                    alterar.setString(3,txtBairro.getText().toUpperCase());
                    alterar.setString(4,txtCidade.getText().toUpperCase());
                    alterar.setString(5,
                    cboEstado.getSelectedItem().toString());
                    alterar.setString(6,ruaAtual);
                    alterar.setString(7,cepAtual);
                    alterar.setString(8,bairroAtual);
                    alterar.setString(9,cidadeAtual);
                    alterar.setString(10,estadoAtual);
                    alterar.executeUpdate();
                    JOptionPane.showMessageDialog(null,
                    "Endereço alterado com sucesso!!!",
                    "Endereço Alterado",
                    JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                }catch(SQLException e)
                {
                    JOptionPane.showMessageDialog(null,
                    "Erro de SQL: " + e.getMessage(),
                    "Erro",JOptionPane.ERROR_MESSAGE);
                }catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,
                    "Erro: " + e.getMessage(),
                    "Erro",JOptionPane.ERROR_MESSAGE);
                }
            }
        }    
    }//GEN-LAST:event_btnCadastrarAlterarActionPerformed

    private void itemCadastrarAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadastrarAlterarActionPerformed
        this.btnCadastrarAlterarActionPerformed(evt);
    }//GEN-LAST:event_itemCadastrarAlterarActionPerformed

    private void itemLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLimparActionPerformed
        this.btnLimparActionPerformed(evt);
    }//GEN-LAST:event_itemLimparActionPerformed

    private void itemFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemFecharActionPerformed
        this.btnFecharActionPerformed(evt);
    }//GEN-LAST:event_itemFecharActionPerformed

    private String ruaAtual,cepAtual,bairroAtual,
            cidadeAtual,estadoAtual;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarAlterar;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JComboBox cboEstado;
    private javax.swing.JMenuItem itemCadastrarAlterar;
    private javax.swing.JMenuItem itemFechar;
    private javax.swing.JMenuItem itemLimpar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblRua;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JFormattedTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtRua;
    // End of variables declaration//GEN-END:variables
}
