/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sistema.manha;

import java.awt.Graphics;
import java.awt.Image;

/**
 *
 * @author Jason Santos
 */
public class Slogan extends javax.swing.JInternalFrame {

    /**
     * Creates new form Slogan
     */
    public Slogan() 
    {
          super(null,false,false,false,false);   
          initComponents();
          try
          {
              imagem=javax.imageio.ImageIO.read
              (new java.net.URL(getClass().
              getResource("slogan.jpg"),"slogan.jpg"));
          }catch (Exception erro){}
    }
    
    public void paint(Graphics fundo)
    {
       fundo.drawImage(imagem,0,0,getWidth(),
               getHeight(),this);
       //primeiro imagem
       //segundo largura inicial
       //terceiro altura inicial
       //quarto pega largura da tela
       //quinto pega a altura da tela
       //sexto this, nesta tela mesma
    }        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        this.moveToBack();
    }//GEN-LAST:event_formMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        this.moveToBack();
    }//GEN-LAST:event_formMousePressed

    protected static Image imagem;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
