/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sistema.manha;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author Jason Santos
 */
public class Splash extends javax.swing.JFrame {

    /**
     * Creates new form Splash
     */
    public Splash() {
        initComponents();
        this.setSize(450,300);
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground
        (new Color(86,126,201));
        ActionListener abrePrincipal=new 
                ActionListener()
        {
            public void actionPerformed(ActionEvent e)
            {
                dispose();//fecha a tela de Splash
                Principal menu=new Principal();
                menu.setVisible(true);
                tempo.stop();
                tempoBarra.stop();
            }
        };
        ActionListener preencheBarra=new 
                ActionListener()
        {
            public void actionPerformed(ActionEvent e)
            {
                progresso=progresso+100;
                progressBar.setValue(progresso);
                //preenche a barra
                progressBar.setStringPainted(true);
                //mostra a porcentagem
            }
        };
        tempo=new Timer(3000,abrePrincipal);
        tempo.start();
        tempoBarra=new Timer(100,preencheBarra);
        tempoBarra.restart();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblModelo = new javax.swing.JLabel();
        lblDe = new javax.swing.JLabel();
        lblSistema = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        lblModelo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblModelo.setText("Modelo");

        lblDe.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblDe.setText("de");

        lblSistema.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblSistema.setText("Sistema");

        progressBar.setMaximum(3000);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblSistema)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(182, 182, 182)
                            .addComponent(lblModelo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(lblDe)))
                .addContainerGap(192, Short.MAX_VALUE))
            .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblModelo)
                .addGap(49, 49, 49)
                .addComponent(lblDe)
                .addGap(52, 52, 52)
                .addComponent(lblSistema)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Splash().setVisible(true);
            }
        });
    }
    
    private Timer tempo,tempoBarra;
    private int progresso=0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDe;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblSistema;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}
