/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package acertarnumero;

import java.util.Random;
import javax.swing.JOptionPane;


 
public class AcertarNumero extends javax.swing.JFrame {

    /**
     * Creates new form AcertarNumero
     */
    public AcertarNumero() {
        initComponents();
        setLocationRelativeTo(null);
        setSize(530,330);
        setResizable(false);
        getRootPane().setDefaultButton(btnArriscar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNumero = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        btnArriscar = new javax.swing.JButton();
        lblDica = new javax.swing.JLabel();
        lblDica2 = new javax.swing.JLabel();
        lblNumeroTentativasRestantes = new javax.swing.JLabel();
        lblNumeroTentativasRestantes2 = new javax.swing.JLabel();
        btnRecomecar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        itemArriscar = new javax.swing.JMenuItem();
        itemRecomecar = new javax.swing.JMenuItem();
        itemFechar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Adivinhe o Número");
        setBackground(new java.awt.Color(240, 82, 202));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblNumero.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblNumero.setText("Número:");

        txtNumero.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        btnArriscar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnArriscar.setText("Arriscar");
        btnArriscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArriscarActionPerformed(evt);
            }
        });

        lblDica.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblDica.setText("Dica:");

        lblDica2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        lblNumeroTentativasRestantes.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblNumeroTentativasRestantes.setText("Número de Tentativas Restantes:");

        lblNumeroTentativasRestantes2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblNumeroTentativasRestantes2.setForeground(new java.awt.Color(255, 0, 0));
        lblNumeroTentativasRestantes2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumeroTentativasRestantes2.setText("10");

        btnRecomecar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnRecomecar.setText("Recomeçar");
        btnRecomecar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecomecarActionPerformed(evt);
            }
        });

        btnFechar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        menuArquivo.setText("Arquivo");
        menuArquivo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        itemArriscar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        itemArriscar.setText("Arriscar");
        itemArriscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemArriscarActionPerformed(evt);
            }
        });
        menuArquivo.add(itemArriscar);

        itemRecomecar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        itemRecomecar.setText("Recomeçar");
        itemRecomecar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRecomecarActionPerformed(evt);
            }
        });
        menuArquivo.add(itemRecomecar);

        itemFechar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        itemFechar.setText("Fechar");
        itemFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemFecharActionPerformed(evt);
            }
        });
        menuArquivo.add(itemFechar);

        jMenuBar1.add(menuArquivo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNumero)
                            .addComponent(lblDica))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(btnArriscar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblDica2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(btnRecomecar)
                        .addGap(64, 64, 64)
                        .addComponent(btnFechar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNumeroTentativasRestantes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNumeroTentativasRestantes2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumero)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnArriscar))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDica2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroTentativasRestantes)
                    .addComponent(lblNumeroTentativasRestantes2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRecomecar)
                    .addComponent(btnFechar))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        fechar();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        fechar();
    }//GEN-LAST:event_formWindowClosing
    
    private void btnRecomecarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecomecarActionPerformed
        recomecar();
    }//GEN-LAST:event_btnRecomecarActionPerformed

    private void btnArriscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArriscarActionPerformed
        arriscar();
    }//GEN-LAST:event_btnArriscarActionPerformed

    private void itemFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemFecharActionPerformed
        fechar();
    }//GEN-LAST:event_itemFecharActionPerformed

    private void itemRecomecarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRecomecarActionPerformed
        recomecar();
    }//GEN-LAST:event_itemRecomecarActionPerformed

    private void itemArriscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemArriscarActionPerformed
        arriscar();
    }//GEN-LAST:event_itemArriscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcertarNumero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcertarNumero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcertarNumero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcertarNumero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AcertarNumero().setVisible(true);
            }
        });
    }
    
    private void arriscar()
    {
        if (!txtNumero.getText().equals(""))
        {
            int numeroUsuario=Integer.parseInt(txtNumero.getText().toString());
            tentativas--;
            lblNumeroTentativasRestantes2.setText(String.valueOf(tentativas));
            if (numero>numeroUsuario)
            {
                lblDica2.setText("Arrisque um valor maior");
                txtNumero.selectAll();
                txtNumero.requestFocus();
            }else if (numero<numeroUsuario)
            {
                lblDica2.setText("Arrisque um valor menor");
                txtNumero.selectAll();
                txtNumero.requestFocus();
            }else
            {
                lblDica2.setText("Parabéns!!! Você acertou!!!");
                JOptionPane.showMessageDialog(null,"Parabéns!!! Você acertou o número!!!","Número",JOptionPane.INFORMATION_MESSAGE);
                Object[] opcoes={"Sim","Não"};
                int retorno=JOptionPane.showOptionDialog(null,"Deseja jogar novamente?","Jogar",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,opcoes,opcoes[0]);
                if (retorno==0)
                {
                    txtNumero.setText("");
                    lblDica2.setText("");
                    lblNumeroTentativasRestantes2.setText("10");
                    tentativas=10;
                    numero=sorteia.nextInt(100)+1;
                }else
                    dispose();                
            }
            if (tentativas==0)
            {
                Object[] opcoes={"Sim","Não"};
                int retorno=JOptionPane.showOptionDialog(null,"Infelizmente você não acertou o número. O número era " + numero + "\nDeseja jogar novamente?","Jogar",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,opcoes,opcoes[0]);
                if (retorno==0)
                {
                    txtNumero.setText("");
                    lblDica2.setText("");
                    lblNumeroTentativasRestantes2.setText("10");
                    tentativas=10;
                    numero=sorteia.nextInt(100)+1;
                }else
                    dispose(); 
            }
        }else
        {
            JOptionPane.showMessageDialog(null,"Informe o número que deseja arriscar","Número",JOptionPane.ERROR_MESSAGE);
            txtNumero.requestFocus();
        }
    }
    
    private void recomecar()
    {
        Object[] opcoes={"Sim","Não"};
	int retorno=JOptionPane.showOptionDialog(null,"Tem certeza que deseja recomeçar?","Recomeçar",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,opcoes,opcoes[0]);
	if (retorno==0)
        {
            txtNumero.setText("");
            lblDica2.setText("");
            lblNumeroTentativasRestantes2.setText("10");
            tentativas=10;
            numero=sorteia.nextInt(100)+1;
        }
    }
    
    private void fechar()
    {
        Object[] opcoes={"Sim","Não"};
	int retorno=JOptionPane.showOptionDialog(null,"Tem certeza que deseja fechar o jogo?","Encerrar",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,opcoes,opcoes[0]);
	if (retorno==0)
            dispose();
    }
    
    private int tentativas=10;
    private Random sorteia=new Random();
    private int numero=sorteia.nextInt(100)+1;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArriscar;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnRecomecar;
    private javax.swing.JMenuItem itemArriscar;
    private javax.swing.JMenuItem itemFechar;
    private javax.swing.JMenuItem itemRecomecar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblDica;
    private javax.swing.JLabel lblDica2;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblNumeroTentativasRestantes;
    private javax.swing.JLabel lblNumeroTentativasRestantes2;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
